project:
  type: website

website:
  title: "alejandro-celis.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/alejandro-celis
      - icon: twitter
        href: https://twitter.com/alej_celis
format:
  html:
    theme: litera
    css: styles.css



